server.port=9081

spring.datasource.url=jdbc:mysql://localhost:3306/nestora_db
spring.datasource.username=root
spring.datasource.password=8568

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true